site_name: Duolingo
repo_name: "Duolingo-2024.1"
repo_url: https://github.com/lipeaaraujo/Duolingo-2024.1

theme:
  logo: assets/images/duolingo-logo.svg
  favicon: assets/images/duolingo-logo.svg
  name: material
  language: pt
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-night 
        name: Modo escuro
        
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Inicio: index.md
  - Planejamento:
    - Aplicativo Escolhido: planejamento/app-escolhido.md
    - Guia de Contribuição: planejamento/guia-contribuicao.md
    - Ferramentas: planejamento/ferramenta.md
    - Comunicação: planejamento/comunicacao.md
    - Cronograma: planejamento/cronograma.md
  - Visão do Produto: visao-produto.md
  - Pré-Rastreabilidade: pre-rastreabilidade.md
  - Elicitação: 
    - Elicitacao de Requisitos:
      - Brainstorming: Elicitacao/ElicitacaodeRequisitos/brainstorm.md
      - Observação/Introspecção: Elicitacao/ElicitacaodeRequisitos/observacao.md
      - StoryTelling: Elicitacao/ElicitacaodeRequisitos/storytelling.md
      - Análise de Protocolo: Elicitacao/ElicitacaodeRequisitos/protocolo.md
      - Junção dos Requisitos: Elicitacao/ElicitacaodeRequisitos/juncao-requisitos.md
    - Priorização de Requisitos:
      - Técnicas:  Elicitacao/priorizacao/tecnicas.md
      - Requisitos Priorizados: Elicitacao/priorizacao/priorizados.md