site_name: Duolingo
repo_name: "Duolingo-2024.1"
repo_url: https://github.com/lipeaaraujo/Duolingo-2024.1

theme:
  logo: assets/images/duolingo-logo.svg
  favicon: assets/images/duolingo-logo.svg
  name: material
  language: pt
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-night 
        name: Modo escuro
        
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Inicio: index.md
  - Apresentações: 
    - Entrega 1 - 01/08: Apresentacoes/apresentacao1.md
    - Entrega 2 - 22/08: Apresentacoes/apresentacao2.md
  - Atas: 
    - Reunião 1 - 25/07: Atas/ata_25_07-1.md
    - Reunião 1 - 27/07: Atas/ata_27_07-1.md
    - Reunião 2 - 27/07: Atas/ata_27_07-2.md
    - Reunião 1 - 29/07: Atas/ata_29_07-1.md
    - Reunião 2 - 29/07: Atas/ata_29_07-2.md
    - Reunião 1 - 30/07: Atas/ata_30_07-1.md
    - Reunião 2 - 30/07: Atas/ata_30_07-2.md
    - Reunião 3 - 30/07: Atas/ata_30_07-3.md
    - Reunião 4 - 30/07: Atas/ata_30_07-4.md
    - Reunião 1 - 31/07: Atas/ata_31_07-1.md
    - Reunião 2 - 31/07: Atas/ata_31_07-2.md
  - Planejamento:
    - Aplicativo Escolhido: Planejamento/app-escolhido.md
    - Guia de Contribuição: Planejamento/guia-contribuicao.md
    - Ferramentas: Planejamento/ferramenta.md
    - Comunicação: Planejamento/comunicacao.md
    - Cronograma: Planejamento/cronograma.md
  - Visão do Produto: visao-produto.md
  - Pré-Rastreabilidade: pre-rastreabilidade.md
  - Elicitação:
    - Introdução: Elicitacao/Elicitacao_introducao.md
    - Elicitação de Requisitos:
      - Brainstorming: Elicitacao/ElicitacaodeRequisitos/brainstorm.md
      - Observação/Introspecção: Elicitacao/ElicitacaodeRequisitos/observacao.md
      - StoryTelling: Elicitacao/ElicitacaodeRequisitos/storytelling.md
      - Análise de Protocolo: Elicitacao/ElicitacaodeRequisitos/protocolo.md
      - Junção dos Requisitos: Elicitacao/ElicitacaodeRequisitos/juncao-requisitos.md
    - Priorização de Requisitos:
      - Técnicas:  Elicitacao/priorizacao/tecnicas.md
      - Requisitos Priorizados: Elicitacao/priorizacao/priorizados.md
  - Modelagem:
    - Léxico: Modelagem/lexico.md
    - Cenarios:
      - Introdução: Modelagem/Cenarios/introducao.md
      - Cenários - Dupla 1: Modelagem/Cenarios/cenarios1.md
      - Cenários - Dupla 2: Modelagem/Cenarios/cenarios2.md
      - Cenários Finais: Modelagem/Cenarios/cenariosFinais.md
    - Casos de uso:
      - Introdução: Modelagem/Casos/introducao.md
      - Diagrama 1: Modelagem/Casos/Caso_de_Uso_1.md
      - Diagrama 2: Modelagem/Casos/Caso_de_Uso_2.md
    - Especificação suplementar: Modelagem/especificacao.md
  - Modelagem Ágil:
    - NFR Framework: ModelagemAgil/nfr-framework.md
    - Product Backlog: ModelagemAgil/product-backlog.md
    - Priorização das Histórias de Usuário: ModelagemAgil/priorizacao-historias.md
    - Minimum Viable Product e Sprint Backlog: ModelagemAgil/sprint-backlog.md
  - Verificação e Validação:
    - Pré-Rastreabilidade: Verificacao-Validacao/rastreabilidade.md
    - Elicitação: 
      - Observação/Introspecção: Verificacao-Validacao/Elicitacao/observacao.md
      - Brainstorming: Verificacao-Validacao/Elicitacao/brainstorming.md
      - Análise de Protocolo: Verificacao-Validacao/Elicitacao/protocolo.md
      - Storytelling: Verificacao-Validacao/Elicitacao/storytelling.md
    - Priorização:
      - Three-Level: Verificacao-Validacao/Priorizacao/three-level-scale.md
      - Moscow:  Verificacao-Validacao/Priorizacao/moscow.md
    - Modelagem:   
      - Cenários: Verificacao-Validacao/Modelagem/cenarios.md
      - Léxicos: Verificacao-Validacao/Modelagem/lexicos.md
      - Casos de uso: Verificacao-Validacao/Modelagem/casos-de-uso.md
    - Modelagem ágil:
      - Especificação Suplementar: Verificacao-Validacao/ModelagemAgil/especificacao.md
      - NFR Framework:  Verificacao-Validacao/ModelagemAgil/nfr.md
      - Backlog:  Verificacao-Validacao/ModelagemAgil/backlog.md
      - Priorização das US: Verificacao-Validacao/ModelagemAgil/priorizacao-us.md
      - MVP: Verificacao-Validacao/ModelagemAgil/mvp.md
      - i*: Verificacao-Validacao/ModelagemAgil/istar.md


